# Generated by Django 6.1.1 on 2026-09-27 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitrationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titration_type', models.CharField(choices=[('SANITIZER', 'Sanitizer'), ('CHLORAGEL', 'Chloragel')], max_length=20)),
                ('min_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titration_limits', to='plants.plant')),
            ],
        ),
    ]
