# Generated by Django 6.1.1 on 2026-09-26 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('titrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChloragelTitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_volume_ml', models.DecimalField(decimal_places=2, default=15.0, editable=False, max_digits=6)),
                ('r9_drops', models.PositiveIntegerField()),
                ('result_percent', models.DecimalField(decimal_places=3, editable=False, max_digits=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CORRECTED', 'Corrected'), ('REVIEW_REQUIRED', 'Review Required')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_chloragel_titrations', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chloragel_titrations', to='plants.plant')),
            ],
        ),
    ]
